### ISSUE TITLE
Portage sous windows?

### ISSUE THREAD

**Issue by DarkCoocky** [Naereen/FreeSMS.py#3]
Quelles modifs devraient être apportées pour que le script tourne dans un environnement windows ?

**Comment by Naereen** [comment]
Bonjour ?

Je ne sais pas trop. Avez-vous essayé ? C'est généralement la meilleure approche.

Je dirai que la seule chose à vérifier (et éventuellement, améliorer) est l'utilisation de fichiers de configuration qui sont normalement stockés dans le dossier du script, ou dans le dossier HOME (sous Debian ou Ubuntu, ~ ou /home/pseudo).

FreeSMS.py utilise ces trois fichiers :
- ./.smsapifreemobile_number.b64
- ./.smsapifreemobile_password.b64
- ./.smsapifreemobile_user.b64

Le code est bien factorisé, avec deux fonctions `testSpecialFile` et `openSpecialFile`. La seule partie que je pense problématique sous Windows est `expanduser('~/')`, mais [sa documentation](https://docs.python.org/3/library/os.path.html#os.path.expanduser) semble dire que c'est supporté sur Windows.

Tenez moi au courant !

**Comment by DarkCoocky** [comment]
La variable d'environnement windows %USERPROFILE% est équivalente au caractère ~ pour accéder au répertoire de l'utilisateur en cours.

Je suis en train de créer les fichiers nécessaires au bon fonctionnement du script pour voir si je pourrais réussir à le lancer (les commandes que vous indiquez pour créer les fichiers ne sont bien entendu valables que pour linux et ne fonctionnent ni dans l'invite de commande windows ni dans powershell)

**Comment by DarkCoocky** [comment]
Fausse manip pour la fin de problème
La variable d'environnement windows %USERPROFILE% est équivalente au caractère ~ pour accéder au répertoire de l'utilisateur en cours.

Je suis en train de créer les fichiers nécessaires au bon fonctionnement du script pour voir si je pourrais réussir à le lancer (les commandes que vous indiquez pour créer les fichiers ne sont bien entendu valables que pour linux et ne fonctionnent ni dans l'invite de commande windows ni dans powershell)

**Comment by Naereen** [comment]
> "les commandes que vous indiquez"

Dans la documentation (https://github.com/Naereen/FreeSMS.py#installation) ? Ou dans le script, si ces dits fichiers ne sont pas présents ?
Oui je pense que le script gagnerait à être plus portable. Mais j'ai trop de mini projets comme ça pour prendre du temps pour chacun pour les rendre portables sous Windows et autres désolé ;-)
Si vous m'aidez, je serai ravi d'inclure les contributions et les changements dans le projet !

**Comment by Naereen** [comment]
Cette ligne aussi n'est pas portable : https://github.com/Naereen/FreeSMS.py/blob/5ed362c3748da8afe600e81d0dc0bf2cd6c4f1dc/FreeSMS.py#L343

Et les lignes qui indiquent comment créer les fichiers ne le sont clairement pas : https://github.com/Naereen/FreeSMS.py/blob/5ed362c3748da8afe600e81d0dc0bf2cd6c4f1dc/FreeSMS.py#L133 et https://github.com/Naereen/FreeSMS.py/blob/5ed362c3748da8afe600e81d0dc0bf2cd6c4f1dc/FreeSMS.py#L134

**Comment by DarkCoocky** [comment]
Vous indiquez des commandes pour aider l'utilisateur à faire l'encodage des infos nécessaires pour l'api mais ces dernières ne fonctionnent que sous linux.
Cependant, les messages pourraient être rendus intéractifs car le module "sys" permet de récupérer le type de système sur lequel est exécuté l'interpréteur python.
https://docs.python.org/3/library/sys.html#sys.platform

**Comment by DarkCoocky** [comment]
> 
> 
> > "les commandes que vous indiquez"
> 
> Dans la documentation (https://github.com/Naereen/FreeSMS.py#installation) ? Ou dans le script, si ces dits fichiers ne sont pas présents ?
> Oui je pense que le script gagnerait à être plus portable. Mais j'ai trop de mini projets comme ça pour prendre du temps pour chacun pour les rendre portables sous Windows et autres désolé ;-)
> Si vous m'aidez, je serai ravi d'inclure les contributions et les changements dans le projet !

Et pour répondre à la question je parlais dans le script. Je vais voir ce que je peux faire pour améliorer la portabilité du script

**Comment by Naereen** [comment]
Ce serait l'approche la plus simple : au début du script, repérer si le script tourne sous GNU/Linux ou Mac OS (là où les `base64` et autres pipes et trucs de Bash marcheront), ou sous Windows. Ou autre, mais là aucun intérêt de tenter de bidouiller pour le rendre plus portable.
Sous Windows, il faudrait juste changer ces lignes et afficher des commandes qui font l'équivalent.

N'hésitez pas à échanger ici, et à ouvrir une fusio-demande (pull request), je serai ravi de l'inclure. Il me reste quelque part un vieil ordi sous Windows mais pas trop le temps de tester moi-même, je vous ferai confiance !

**Comment by DarkCoocky** [comment]
C'est d'ores et déjà ajouté au script car si on est sous windows j'ai besoin de récupérer le nom de l'utilisateur windows connecté pour accéder au penchant windows du home

**Comment by DarkCoocky** [comment]
J'ai réussi à faire en sorte que le script accède à tous les fichiers dont il a besoin mais j'ai un problème au décodage des chaines encodées en base 64 car le programme envoie au json des type byte au lieu des types string

`File "c:\Users\PH\Downloads\FreeSMS.py-master - 1\FreeSMS.py-master\FreeSMS.py", line 362, in <module>
    results = main(sys.argv[1:])
  File "c:\Users\PH\Downloads\FreeSMS.py-master - 1\FreeSMS.py-master\FreeSMS.py", line 355, in main
    answers = send_sms(text, sleep_duration=sleep_duration)
  File "c:\Users\PH\Downloads\FreeSMS.py-master - 1\FreeSMS.py-master\FreeSMS.py", line 243, in send_sms
    string_query = json.dumps(dictQuery, sort_keys=True, indent=4)
  File "C:\Users\PH\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 234, in dumps return cls(
  File "C:\Users\PH\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Users\PH\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\PH\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\PH\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\PH\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable`

**Comment by Naereen** [comment]
Ah oui, je crois que je forçais encore à utiliser Python 2 chez moi, j'avais eu la flemme de bien gérer les strings localisées en UTF-8 plutôt que des bytes.

**Comment by DarkCoocky** [comment]
En fouinant un peu j'aurais une solution sous python 3 pour gérer la conversion bytes -> string. Je testerai demain.
L'idéal serait que le script soit totalement opérationnel en python 3 surtout que le 2 est en fin de vie 😅

**Comment by Naereen** [comment]
Oui je suis parfaitement au courant (cf. <https://pythonclock.org/> !), j'ai juste manqué de temps...
Et comme « ça marche chez moi » (et que je n'avais jamais eu de retour d'une autre personne intéressée), je n'avais même pas noté la conversion en Py3K comme valant la peine d'être faite.
Merci d'avance !

**Comment by DarkCoocky** [comment]
La conversion octets vers chaine de caractères n'est pas suffisante, le json n'arrive toujours pas à sérialiser.
Par ailleurs, cela ne vaudrait-il pas le coup d'abandonner le support du python 2 étant donné que comme vous l'indiqué, python 2 est déjà mort.

**Comment by DarkCoocky** [comment]
Du coup j'ai corrigé les problèmes de sérialisation json, augmenté la compatibilité avec windows et ajouté des messages d'aide variables selon la plateforme (j'ai fait windows, enfin j'ai donné les commandes powershell uniquement et gardé vos commandes linux).
Reste à voir comment je peux vous transmettre les modifications (j'ai cloné votre dépot et fait les modifs dans le dossier cloné mais j'ai pas les droits d'accès pour remonter les modifs)

**Comment by DarkCoocky** [comment]
Pull Request faite. Fermeture du ticket.
